version 1.1-7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1750,6 +1750,21 @@ PKG_CPPFLAGS=$CPPFLAGS
 PKG_CFLAGS=$CFLAGS
 PKG_LDFLAGS=$LDFLAGS
 
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+LDFLAGS=`"${R_HOME}/bin/R" CMD config LDFLAGS`
+
+echo "CC:" $CC
+echo "CFLAGS:" $CFLAGS
+echo "CPPFLAGS:" $CPPFLAGS
+echo "LDFLAGS:" $LDFLAGS
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
